fix: organization of the code

diff --git a/utilities/yt_download b/utilities/yt_download
--- a/utilities/yt_download
+++ b/utilities/yt_download
@@ -2,9 +2,9 @@
 
 #============================================|
 #	Downloads youtube audio
-#	created by: Jean0t
+#	created by: Joao Mauricio
 #	github: github.com/jean0t
-#	version: 1.2
+#	version: 1.3
 #============================================|
 #	Changelog
 #
@@ -19,13 +19,21 @@
 #	1.2:
 #		- Test if the link passed is
 #		  a valid youtube link
+#
+#	1.3:
+#		- More organized code with
+#		  functions and a menu to
+#		  interact with the user.
+#
+#		- Now provides info about
+#		  the app with parameters
+#
+#		fixed:
+#			- download of multiple
+#			  songs in a playlist
+#			  without explicit allowing. 
 #============================================|
-# INFORMATION ABOUT THE SOFTWARE
 
-version='1.2'
-[[ "$1" = "-v" || "$1" == "--version" ]] && { echo -e "Version \E[1;34m${version}\E[0m" ; exit 0 ; }
-
-#============================================|
 # VERIFICATIONS
 
 # Do not allow root to run
@@ -41,26 +49,71 @@ version='1.2'
 [[ ! -e "$HOME/Downloads/Youtube_Download" ]] \
 && { echo 'created directory ~Downloads/Youtube_Download' ; mkdir -p "$HOME/Downloads/Youtube_Download" ; }
 
-# test if there are parameters
-[[ $# -eq 0 ]] && { echo 'you need to pass an youtube link to download' ; exit 1 ; }
+#============================================| GLOBAL VARIABLES
 
-# test if the link is valid
-youtube_regex='^(https?\:\/\/)?(www\.youtube\.com|youtu\.?be)\/.+$'
-[[ $1 =~ $youtube_regex ]] || { echo 'It is not a valid link, please provide a https://youtube.com/...' ; exit 1 ; }
-
-#============================================|
-# GLOBAL VARIABLES
+version='1.3'
 output_directory="$HOME/Downloads/Youtube_Download/%(title)s.%(ext)s"
-#============================================|
 
-#	START THE PROGRAM
+#============================================| FUNCTIONS
 
-echo 'Starting the download...'
-if yt-dlp -x -f bestaudio -o "$output_directory" --embed-thumbnail "$@" >&- 2>&- ; then
-	echo 'Download was successful, saved in:'
-	echo "$HOME/Downloads/Youtube_Download"
-	exit 0
-else
-	echo $'\E[31;1mAn error has occurred\E[0m\nDo you have the python module Mutagen?'
-	exit 1
-fi
+function version() {
+	echo "version ${version}"
+}
+
+function help() {
+	cat <<'EOF'
+usage: ./yt_download [OPTIONS] LINK
+
+	OPTIONS:
+		-a|--audio	Downloads the audio of the video
+
+		-h|--help 	Gets info about the software
+
+		-v|--version	Gets the current version
+
+
+	REASON OF COMMON ISSUES:
+		- Absence of ffmpeg on the system
+		- Absence of the module mutagen
+EOF
+}
+
+function download_audio() {
+
+	# test if there are parameters
+	[[ $# -eq 0 ]] && { echo 'you need to pass an youtube link to download' ; exit 1 ; }
+
+	# test if the link is valid
+	local youtube_regex='^(https?\:\/\/)?(www\.youtube\.com|youtu\.?be)\/.+$'
+	[[ $1 =~ $youtube_regex ]] || { echo 'It is not a valid link, please provide a https://youtube.com/...' ; exit 1 ; }
+
+
+	echo 'Starting the download...'
+	if yt-dlp -x -f bestaudio -o "$output_directory" --embed-thumbnail --no-playlist "$@" >&- 2>&- ; then
+		echo 'Download was successful, saved in:'
+		echo "$HOME/Downloads/Youtube_Download"
+		exit 0
+	else
+		echo $'\E[31;1mAn error has occurred.\E[0m\nUse -h or --help to know more.'
+		exit 1
+	fi
+}
+
+#============================================|START THE PROGRAM
+
+
+case "$1" in
+	-a|--audio)
+		shift
+		download_audio "$1"
+		;;
+
+	-v|--version)
+		version
+		;;
+
+	-h|--help|*)
+		help
+		;;
+
+esac
